### ISSUE TITLE
Reworking the syntax checker

### ISSUE THREAD

**Issue by OwlyCode** [friendsoftwig/twigcs#66]
I'm currently reworking the way Twigcs handles basic style checks like counting the number of spaces, checking that something is lowercased etc... It will be a separated engine that can works along the unused macros/variable checkers. At the moment it is called "RegEngine" because it heavily uses regular expression.

The branch: https://github.com/OwlyCode/twigcs/commits/experimental

I expect this rework to fix the following issues :

- [x] #56 Array rule
- [x] #60 Does not respect both include syntaxes
- [x] #62 Support extended white space control operators in Twig templates
- [x] #63 False positive no space before "("
- [x] #64 False positive 1 space(s) after "-" with negative numbers

**Comment by OwlyCode** [comment]
This landed in the master branch. I will manage to get some time for a beta release, hopefully next week!

**Comment by stof** [comment]
please also describe the upgrade guide (our current ruleset file references classes which are removed by your refactoring).

**Comment by OwlyCode** [comment]
Here's a quick update: I'm still working on this! I have had less time lately (became CTO at my workplace) but kept working on the rewrite.

The new engine is completed and fixes all the problems listed above and also prepares for the future (like arrow functions support). It sleeps in the master, waiting to be tagged for beta. I just added a branch with a quick method for configuring the engine for simpler needs that should be merged in september.

Next steps are:

- Finishing the quick configuration system.
- Writing the new documentation
    - how to upgrade a ruleset from a previous version?
    - Basic: how to customize the new engine using quick configuration?
    - Advanced: how to write a fully customized ruleset?
- Cleaning some classes now that major changes should no longer be required.
- Shipping a beta so you can tell me if some of your needs are still unadressed.

Thank you for using Twigcs, and thank you for your patience!

**Comment by OwlyCode** [comment]
All is done, we should be ready for 4.0-beta soon!

**Comment by oallain** [comment]
Really nice work 👍
